services:
  - type: web
    name: mortgage-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_dash:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 